### ISSUE TITLE
Mark item class active instead of link class?

### ISSUE THREAD

**Issue by cercos** [icings/menu#3]
Is there a way to make the item class be marked active instead of the link class?  I set the current to true on the item options but it still doesnt get marked as active unless im missing something

**Comment by ndm2** [comment]
I'm not sure that I can follow. Are you saying that using the `current` option doesn't work, or that you want it to generate different HTML?

Ideally provide an example of your code, and the HTML that you'd expect it to generate.

**Comment by cercos** [comment]
Sorry had a typo...sorted it all out.

**Comment by ndm2** [comment]
OK...
