### ISSUE TITLE
HTML escaping not working

### ISSUE THREAD

**Issue by cercos** [icings/menu#4]
```
$menu->addChild('<span>Home</span>', [
    'uri' => '#!',
    'escape' => false,
    'attributes' => [
        'class' => 'waves-effect waves-light'
    ]
]);
```

Still displays `<span>Home</span> `

**Comment by ndm2** [comment]
Until this is fixed, use the `extras` option, like:

    'extras' => ['escapeLabel' => false]

`escape` would work there too, but that would also disable attribute escaping, which you should only disable if you really need to.

**Comment by cercos** [comment]
ok thanks that worked
