### ISSUE TITLE
How to mark a link as active?

### ISSUE THREAD

**Issue by zhkuskov** [icings/menu#7]
My menu has the following code:

 <li class="nav-item dropdown"> 
            
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false"> 
          
          <i class="fas fa-user"></i> 
          
          </a> 
          
          <div class="dropdown-menu dropdown-menu-left dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333"> 
          <a class="dropdown-item" href="#">Action</a> 
          
          <a class="dropdown-item" href="#">Another action</a> 
          
          <a class="dropdown-item" href="#">Something else here</a> 
          
          </div> 
          
          </li>

How to make the links in the drop-down menu are marked with the class "active" automatically when they
matched?
Thank you! Sorry for my English ..

**Comment by ndm2** [comment]
Hi @zhkuskov, I'm not really sure I understand what exactly you are asking. The HTML snippet doesn't contain any URLs, so there's supposedly nothing that the plugin could automatically match against. It may help to clarify if you provide the menu builder code that you are using to build your menu, and show an example of the HTML output that you are trying to produce.

Generally determining the active item works out of the box, given that you are providing matching URLs / URL arrays to the menu builder's `addChild()` method via the `uri` and/or `routes` option, see **https://github.com/icings/menu/blob/3.0.0/docs/index.md#basic-usage** and **https://github.com/icings/menu/blob/3.0.0/docs/index.md#determining-the-active-item**.

**Comment by zhkuskov** [comment]
Ok))
My code: 

<?php
$this->Menu->setConfig([ 
    'templates' => [ 
        'menu' => '<ul{{attrs}}>{{items}}</ul>',     
        'nest' => '<div{{attrs}}>{{items}}</div>',     
        'item' => '<li{{attrs}}>{{link}}{{nest}}</li>', 
        'link' => '<a href="{{url}}"{{attrs}}>{{label}}</a>', 
        'text' => '<span{{attrs}}>{{label}}</span>' 
    ],
    
    'leafClass' => 'nav-item',
    'ancestorClass' => 'active',
    'matchingDepth' => 3
    
]);

$linkAttributes =  [ 
    'class' => 'nav-link waves-effect'
];

$menu = $this->Menu->create(
    'menu-right',
    [
        'menuAttributes' => [ 
            'class' => 'navbar-nav nav-flex-icons' 
        ],
        
         'nestedMenuClass' => 'dropdown-menu dropdown-menu-left dropdown-default', 
         'branchClass' => 'nav-item dropdown'
    ]
); 

$menu->addChild( 
    __('FacebookLink'), 
    [
        'uri' => 'https://www.facebook.com',
        'label' => '<i class="fab fa-facebook-f"></i>',
        'escapeLabel' => false,
        'linkAttributes' => [
            'class' => 'nav-link waves-effect',
            'target' => '_blank'
        ]
        
    ]
); 

$menu->addChild( 
    __('TwitterLink'), 
    [
        'uri' => 'https://twitter.com',
        'label' => '<i class="fab fa-twitter"></i>',
        'escapeLabel' => false,
        'linkAttributes' => [
            'class' => 'nav-link waves-effect',
            'target' => '_blank'
        ]
        
    ]
); 

$menu->addChild( 
    'AdminMenu', 
    [
        'uri' => '#',
        'label' => '<i class="fas fa-tachometer-alt"></i>',
        'escapeLabel' => false,
        'linkAttributes' => [
            'class' => 'nav-link dropdown-toggle',
            'id' => 'navbarDropdownMenuLink-Admin',
            'data-toggle' => 'dropdown',
            'aria-haspopup' => 'true', 
            'aria-expanded' => 'false'
        ],
        'nestAttributes' => [
            'aria-labelledby' => 'navbarDropdownMenuLink-Admin'
        ],
        
    ]
); 

$menu['AdminMenu']->addChild( 
    __('Articles'), 
    [
        'uri' => [
            'plugin' => false, 
            'prefix' => 'admin', 
            'controller' => 'Articles', 
            'action' => 'index'
        ],
        'linkAttributes' => [
            'class' => 'dropdown-item'
        ],
        'templates' => [
            'item' => '{{link}}'
        ],
        
    ]
); 

$menu['AdminMenu']->addChild( 
    __('Keywords'), 
    [
        'uri' => [
            'plugin' => false, 
            'prefix' => 'admin', 
            'controller' => 'Keywords', 
            'action' => 'index'
        ],
        'linkAttributes' => [
            'class' => 'dropdown-item'
        ],
        'templates' => [
            'item' => '{{link}}'
        ],
        
    ]
); 

$menu['AdminMenu']->addChild( 
    __('Attachments'), 
    [
        'uri' => [
            'plugin' => false, 
            'prefix' => 'admin', 
            'controller' => 'Attachments', 
            'action' => 'index'
        ],
        'linkAttributes' => [
            'class' => 'dropdown-item'
        ],
        'templates' => [
            'item' => '{{link}}'
        ],
        
    ]
); 

$menu['AdminMenu']->addChild( 
    __('Users'), 
    [
        'uri' => [
            'plugin' => false, 
            'prefix' => 'admin', 
            'controller' => 'Users', 
            'action' => 'index'
        ],
        'linkAttributes' => [
            'class' => 'dropdown-item'
        ],
        'templates' => [
            'item' => '{{link}}'
        ],
        
    ]
); 

echo $this->Menu->render('menu-right');
?>      

I need the AdminMenu links to automatically be marked as active when I have the corresponding page open.

For example, when i go to page by url: "https://example.com/admin/articles/index" - i get this html generated:

<ul class="navbar-nav nav-flex-icons">

<li class="nav-item">
<a href="https://www.facebook.com" class="nav-link waves-effect" target="_blank">
<i class="fab fa-facebook-f"></i>
</a>
</li>

<li class="nav-item">
<a href="https://twitter.com" class="nav-link waves-effect" target="_blank">
<i class="fab fa-twitter"></i>
</a>
</li>

<li class="active nav-item dropdown">

<a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-Admin" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<i class="fas fa-tachometer-alt"></i>
</a>

<div aria-labelledby="navbarDropdownMenuLink-Admin" class="dropdown-menu dropdown-menu-left dropdown-default">

<a href="/admin/articles" class="dropdown-item">Articles</a>

<a href="/admin/keywords" class="dropdown-item">Keywords</a>

<a href="/admin/attachments" class="dropdown-item">Attachments</a>

<a href="/admin/users" class="dropdown-item">Users</a>

</div>

</li>

</ul>  

But I need the Articles link to have a class: "dropdown-item active" - instead of "dropdown-item"

And I need the "active" class to be added automatically.

**Comment by ndm2** [comment]
I see... that's not really supported (yet), the class for matched elements is currently only being set to the item template.

The cleanest way to work around this would be to implement a custom renderer that overrides `StringTemplateRenderer::_renderLinkElement()` and injects the active class for the current/selected item, something along the lines of this:

**src/Menu/Renderer/CustomStringTemplateRenderer.php**

```php
namespace App\Menu\Renderer;

use Icings\Menu\Renderer\StringTemplateRenderer;
use Knp\Menu\ItemInterface;

class CustomStringTemplateRenderer extends StringTemplateRenderer
{
	protected function _renderLinkElement(ItemInterface $item, array $options)
	{
		if ($item->isCurrent()) {
			$class = (array)$item->getLinkAttribute('class');
			$class[] = $options['currentClass'];
			$item->setLinkAttribute('class', implode(' ', $class));
		}

		return parent::_renderLinkElement($item, $options);
	}
}
```

Then in your view template configure the custom renderer, which (currently) also requires to create the matcher and voters manually, like this:

```php
use App\Menu\Renderer\CustomStringTemplateRenderer;
use Icings\Menu\Matcher\Matcher;
use Icings\Menu\Matcher\Voter\UrlVoter;

// ...

$matcher = new Matcher();
$matcher->addVoter(new UrlVoter($this->getRequest())); // CakePHP 3.7+
//$matcher->addVoter(new UrlVoter($this->request)); // CakePHP < 3.7

$this->Menu->setConfig([
	// ...

	'renderer' => new CustomStringTemplateRenderer($matcher),
]);
```

Once I have a little more free time I'll check if I can maybe add native support for optionally moving classes into the link template.

**Comment by ndm2** [comment]
Oh and in case this causes problems with your other, non-dropdown links that would receive the class too, then you could use the `extras` options to pass in a flag:

```php
$menu['AdminMenu']->addChild( 
	__('Label'), 
	[
		// ...

		'extras' => [
			'setCurrentClassOnLink' => true,
		],
	]
);
```

and make adding the class in the custom renderer conditional:

```php
if ($item->getExtra('setCurrentClassOnLink') && $item->isCurrent()) {
	// ...
}
```

**Comment by zhkuskov** [comment]
Thank you very much for your help and detailed response!

**Comment by ndm2** [comment]
You're welcome... I'll reopen this for now, so that I don't forget about the possible enhancement :)

**Comment by zhkuskov** [comment]
Hi, )
I took your help.  But it seems to have found a typo in this answer:
https://github.com/icings/menu/issues/7#issuecomment-496293300 

The code from this answer does not add an active class.
Instead of this:
```
if ($item->isCurrent()) 
```
- i used this condition:
```
 if ($this->_matcher->isCurrent($item))
```

After that, everything worked. 

The solution was peeped in the plugin code in this file:
src/Renderer/StringTemplateRenderer.php

Thanks again!

**Comment by ndm2** [comment]
Sorry, my bad, I've updated the examples :)

**Comment by ndm2** [comment]
For those that are interested, I've added support for inheriting/consuming auto-generated item classes in the **[feature/inherit-consume-item-classes](https://github.com/icings/menu/tree/feature/inherit-consume-item-classes)** branch (it can be required via composer as `icings/menu:feature/inherit-consume-item-classes-dev`). I'm not sure yet how I should feel about it, and if this will make it into the plugin, please leave your feedback here if you have any.

Surely this doesn't cover all possible situations, but IMHO it's the best compromise without adding lots of configuration and complexity.

See the **[Inheriting/Consuming auto-generated item classes](https://github.com/icings/menu/blob/feature/inherit-consume-item-classes/docs/index.md#inheritingconsuming-auto-generated-item-classes)** section in the docs for details on how it works.

**Comment by ndm2** [comment]
This has now been integrated into 4.x
