### ISSUE TITLE
Apply ACL control over the menu

### ISSUE THREAD

**Issue by savedario** [icings/menu#8]
More of a question than an issue:
I am preparing the migration of a 2.x app to 3.x.
It seems the menu is build inside the view itself.
In that case I would need to pass the View also an ACL object of some kind to build the menu according to the user's permissions.
Intuitively, I would have done that inside the controller/component and only render the menu in the View.
How should I go about building a menu that consider user permissions ?

**Comment by ndm2** [comment]
I'm not really sure what exactly you are asking... is your question whether passing ACL information to the view is a good idea? Or are you asking how to build a menu outside of a view?

**Comment by savedario** [comment]
Thanks for answering.
A bit of both. Since you built the plugin, I was wondering how you would recommend to do it.
I think I can handle passing the ACL to the view, so perhaps the question really is: can I build the menu outside of the view ?

**Comment by ndm2** [comment]
Well, if you ask me, I'd say that access control is part of all layers, model, view/presentation, controller, in every layer there's something where authorization has its purpose, so I'd say that building the menu in the view with respect to authorization is generally fine, and that's also what I usually do personally.

Building the menu outside of the view has its use cases too I guess, and yes it's possible, see the [**Using the library directly**](https://github.com/icings/menu/blob/3.0.0/docs/index.md#using-the-library-directly) section in the docs. Here's a quick and dirty example, say `$user` is an identity object provided by [**the authorization plugin**](https://github.com/cakephp/authorization):

```php
use Icings\Menu\Integration\PerItemVotersExtension;
use Icings\Menu\Integration\RoutingExtension;
use Icings\Menu\Integration\TemplaterExtension;
use Icings\Menu\MenuFactory;

$factory = new MenuFactory();
$factory->addExtension(new RoutingExtension());
$factory->addExtension(new PerItemVotersExtension());
$factory->addExtension(new TemplaterExtension());

$menu = $factory->createItem('main');
$menu->addChild('Home', ['uri' => ['controller' => 'Pages', 'action' => 'display', 'home']]);

if ($user->can('access', '/settings')->getStatus()) {
    $menu->addChild('Settings', ['uri' => ['controller' => 'Settings', 'action' => 'index']]);
}
if ($user->can('access', '/logs')->getStatus()) {
    $menu->addChild('Logs', ['uri' => ['controller' => 'Logs', 'action' => 'index']]);
}
// ...
```

You'd pass such a menu object to the view, and then either render it manually:

```php
use Icings\Menu\Matcher\Matcher;
use Icings\Menu\Matcher\Voter\UrlVoter;
use Icings\Menu\Renderer\StringTemplateRenderer;

$matcher = new Matcher();
$matcher->addVoter(new UrlVoter($this->getRequest());

$renderer = new StringTemplateRenderer($matcher);
echo $renderer->render($menu);
```

or via the helper's `render()` method:

```php
echo $this->Menu->render($menu);
```

**Comment by savedario** [comment]
Thanks for taking the time to answer.

**Comment by ndm2** [comment]
You're welcome.
